name: Deploy to AWS Lambda

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./ChauMundo/ChauMundo.csproj

      - name: Build project
        run: dotnet publish ./ChauMundo/ChauMundo.csproj -c Release -o ./publish

      - name: Zip Lambda package
        run: |
          cd publish
          zip -r ../my-lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp my-lambda.zip s3://${{ secrets.S3_BUCKET_PREFIX }}-dotnetcodebucket/my-lambda.zip

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name aws-lambda-dotnet-code --s3-bucket ${{ secrets.S3_BUCKET_PREFIX }}-dotnetcodebucket --s3-key my-lambda.zip
